### ISSUE TITLE
Compile Boost

### ISSUE THREAD

**Issue by petrasvestartas** [fel88/DeepNestPort#1]
Hi,

I have no experience running .bat files, hence I have a question how to compile minkowski cpp files correctly.

I have downloaded Boost 1.68 version, added to environmental variables. I was using boost before and it works on visual studio.

What I am doing wrong in following procedure?

1. I open compile.bat using text editor and add path directory like this:
cl /Ox /Ob2 /Oi /Ot /Oy- /GL /GF /Gm- /MD /GS- /arch:AVX2 /fp:fast -I <**C:\Libs\boost_1_68_0**> /LD minkowski.cc

2. Then run visual studio command prompt (as administrator), navigate to correct directory and type compile. But I get this exception:

_C:\Libs\DeepNestPort-master\DeepNestPort-master\Minkowski>cl /Ox /Ob2 /Oi /Ot /Oy- /GL /GF /Gm- /MD /GS- /arch:AVX2 /fp:fast -I  0<C:\Libs\boost_1_68_0 1>/LD
Access is denied_.

I tried adding these directories and they all have the same issue:
C:\Libs\boost_1_68_0
C:\Libs\boost_1_68_0\boost
C:\Libs\boost_1_68_0\lib64-msvc-14.0

![2018-11-12](https://user-images.githubusercontent.com/18013985/48347486-a8f9a180-e67e-11e8-8daf-1cffddbbc472.png)

**Comment by fel88** [comment]
Hi, 
1. it seems you wrote wrong path:
```
cl /Ox /Ob2 /Oi /Ot /Oy- /GL /GF /Gm- /MD /GS- /arch:AVX2 /fp:fast -I < C:\Libs\boost_1_68_0 > /LD minkowski.cc
```
should be
```
cl /Ox /Ob2 /Oi /Ot /Oy- /GL /GF /Gm- /MD /GS- /arch:AVX2 /fp:fast -I " C:\Libs\boost_1_68_0"  /LD minkowski.cc
```
for example my compile.bat :
```
cl /Ox /Ob2 /Oi /Ot /Oy- /GL /GF /Gm- /MD /GS- /arch:AVX2 /fp:fast -I "C:\Users\fel\Downloads\boost_1_62_0\boost_1_62_0" /LD minkowski.cc
```
2. You should use 1.62 Boost version

3. Access denied: i think, you should run Command Prompt as an Administrator

**Comment by petrasvestartas** [comment]
Dear @fel88 ,

Thank you for a reply, after changing to "path" it worked.

Now I will try to run visual studio project.

Do I need to reference generated .dll somehow specially or it can be referenced typically in visual studio project?

**Comment by fel88** [comment]
Minkowski.dll is unmanaged dll. Just put minkowski.dll in bin\Debug (or bin\Release) folder after building project. Then you can run DeepNestPort.exe

**Comment by petrasvestartas** [comment]
Dear @fel88 ,

Thank you it is working and nesting elements.

I would like to ask if I run your software on other computer, would I need to download boost and compile it again, or it would be just enough to have minkowski.dll together with .exe file?

**Comment by petrasvestartas** [comment]
I will try to set properties of sheets parts and settings, but if you can show an example of simple console application it would be super nice:)

**Comment by fel88** [comment]
Ok, no problem.

**Comment by petrasvestartas** [comment]
Thank you for console application.

Do you have an example of .xml file as an input to main function?
What would be the way to type  polygons manually by defining their coordinates instead of using .xml file?

For instance if I would like to nest 10 triangles (or other types of polylines) by specifying their coordinates.
The pseudo code I imagine:

```
for(int i = 0 ; i < 10; i++){
  var polygon = new SomePolygonClass();
  polygon.Add(0,0);
  polygon.Add(0,10);
  polygon.Add(10,10);
  
  sample.AddElementToNest(polygon );
}
```

**Comment by fel88** [comment]
1. I've added the example of .xml file.
1. You can run DeenNestConsole.exe with 'sample' argument (DeepNestConsole sample). 
Look at LoadSampleData method. It is exactly what you want.

**Comment by petrasvestartas** [comment]
Thank you very much it works very well:)
