### ISSUE TITLE
Accepting DXF as input

### ISSUE THREAD

**Issue by Mazraq** [fel88/DeepNestPort#10]
is it possible to add DXF as input?

**Comment by fel88** [comment]
Please check forks (e.g. https://github.com/Daniel-t-1/DeepNestPort), the problem is probably already solved there.

**Comment by tgckrks** [comment]
We already use this fork  (https://github.com/Daniel-t-1/DeepNestPort), but still we couldn't import and export dxf files. When we examined this code, we saw the dxf export code that is not completed and  we couldn't find the dxf import code. Do you have fully completed code. If there is, could you please share with us?

**Comment by fel88** [comment]
I'll add dxf support in few days.

**Comment by tgckrks** [comment]
Thank you for attention, I will be waiting. I would be very glad, if you upload dxf support.

**Comment by fel88** [comment]
Please check the latest commit. Maybe it will be enough for you purposes.

**Comment by tgckrks** [comment]
Yes, we check the latest commit and added DXF as inputs. However, the system does not work when import different dxf files to the system. Please, could you share dxf files if you have a code or application that can import dxf files ?

**Comment by fel88** [comment]
[Release.zip](https://github.com/fel88/DeepNestPort/files/6570711/Release.zip)

**Comment by tgckrks** [comment]
Yes it is work for your DeepNestPort application. I've designed a decision support system like yours. In this decision support system, your dxf file samples are not import. Actually, all libraries added. Can you help me if I send you my decision support system?

**Comment by fel88** [comment]
I can take a look.

**Comment by 9swampy** [comment]
I've just been looking at the SvgParser load code but couldn't get it to work; then found it doesn't seem to be wired up to the UI at all. Before DXF import was possible was SVG import working/should it be working now?

**Comment by fel88** [comment]
Now it should work as before (Input tab -> load detail)
