### ISSUE TITLE
'minkowski.cc': No such file or directory

### ISSUE THREAD

**Issue by kelyamany** [fel88/DeepNestPort#11]
I tried to follow the instructions to compile minkowski.dll but I get the following error:

`c1xx: fatal error C1083: Cannot open source file: 'minkowski.cc': No such file or directory`

I downloaded [Boost 1.62](https://www.boost.org/users/history/version_1_62_0.html) and unpacked it to C:\boost_1_62_0 as mentioned in the instructions

Did I miss something?

**Comment by fel88** [comment]
Are the files compile.bat and minkowski.cc in the same directory?

**Comment by kelyamany** [comment]
> Are the files compile.bat and minkowski.cc in the same directory?

Yes, the compile.bat and both minkowski cc and h files are in this directory:
`\DeepNestPort\Minkowski`

**Comment by fel88** [comment]
You probably try to run compile.bat from another directory.
You should enter the Minkowski directory first 
`cd Minkowski`
then run compile.bat
`compile.bat`

**Comment by kelyamany** [comment]
> You probably try to run compile.bat from another directory.
> You should enter the Minkowski directory first
> `cd Minkowski`
> then run compile.bat
> `compile.bat`

Exactly what was missing, now it works. Thanks a lot ))
