### ISSUE TITLE
System.badimageformatexception in minkowski DLL 

### ISSUE THREAD

**Issue by weltondepaula** [fel88/DeepNestPort#13]
Hi guys, I need your help.

I'm compiling the DLL as the example described by fel88, it is correctly generating the dll.
When I put the dll together with DeepNestPort.exe folder and run the application the exception is generated.

I tried to change the dll path, but the error remains.

Has anyone been through this, or has any idea to help me.
Do I need to install something else?

Thanks.
![WhatsApp Image 2021-06-28 at 13 47 24 (1)](https://user-images.githubusercontent.com/1889348/123675295-ed7ae100-d818-11eb-8f7a-d6c1ca95ff14.jpeg)
![WhatsApp Image 2021-06-28 at 13 47 24 (2)](https://user-images.githubusercontent.com/1889348/123675298-ee137780-d818-11eb-932f-d2fb7f9661ea.jpeg)
![WhatsApp Image 2021-06-28 at 13 47 24 (3)](https://user-images.githubusercontent.com/1889348/123675300-eeac0e00-d818-11eb-8270-c32926acc592.jpeg)
![WhatsApp Image 2021-06-28 at 13 47 24](https://user-images.githubusercontent.com/1889348/123675302-ef44a480-d818-11eb-8454-b254ee1a336f.jpeg)

**Comment by fel88** [comment]
Hi, you probably have x86/x64 mismatch problem. 
Try switching the compiler to x64 
https://github.com/fel88/DeepNestPort/issues/2

You can also try to set 'platform target' to x86
![image](https://user-images.githubusercontent.com/15663687/123731887-bc92be80-d8a1-11eb-896e-bd585a62f9c1.png)

**Comment by 9swampy** [comment]
C isn't in my comfort zone and I've been having fun with the DLL compilations too. I'd concur with the suggestion to try flip over to x86 and found a simpler command in compile.bat works in some cases where the full didn't;

> cl /Ox -I "D:\boost\boost_1_62_0" /LD minkowski.cc

Sorry, I don't have the reference of where I got that suggestion from; it's in one of the DeepNestPort or DeepNest issues.

**Comment by weltondepaula** [comment]
Hello guys, thanks so much for help. 

Fell88, your tip solved my problem. I did some changes im my project to use x64. 

When I published to instal I have beem change in the TragetPlatform too.

In select the setup project > properties and change the TragetPlatform to x64.

Thanks.
