### ISSUE TITLE
Instructions on running / building DeepNestPort

### ISSUE THREAD

**Issue by DavidLeonardWenzel** [fel88/DeepNestPort#14]
Hey fel88, first of all, thank you for the great work on this port! 

I was able to follow the instructions on compiling the minkowski dll, but wondered about how to proceed to get an actual executable of the nesting program shown in the images. 
Would it be possible to include instructions on how to run the program? I tried building using the DeepNestPort.sln in Visual Studio Code as well as running DeepNestPort/Program.cs, however, no launch.json or build or exe can be found.

**Comment by fel88** [comment]
Hi, you must use Visual Studio (e.g. community edition) not VS Code to compile DeepNestPort.sln

**Comment by DavidLeonardWenzel** [comment]
Thank you for your answer! I was able to compile the port in Visual Studio after taking out all DXF references, as I was unable to compile the separate DXF repository. Is my assumption correct that you need to clone and build the dxf import/export project separately?  (https://github.com/IxMilia/Dxf)

**Comment by fel88** [comment]
> Thank you for your answer! I was able to compile the port in Visual Studio after taking out all DXF references in the source, as I was unable to compile the separate DXF repository. 

IxMilia/Dxf is a nuget package. You should probably just restore the nuget packages to fix references. Try click right button to the DeepNestLib project in the Solution explorer tree and select 'Manage NuGet Packages'
![image](https://user-images.githubusercontent.com/15663687/127018752-141a4673-b1e7-479a-8698-e8ad584561d4.png)

Then click to 'Restore" button in the upper right corner
![image](https://user-images.githubusercontent.com/15663687/127019084-1e8891cb-9a90-451d-ace4-17a80584d043.png)

Also you can try 'dotnet restore' command in the 'Package manager console'
![image](https://user-images.githubusercontent.com/15663687/127019656-e2847004-6984-409b-ae7d-8c56b7649e19.png)





> Is my assumption correct that you need to clone and build the dxf import/export project separately? (https://github.com/IxMilia/Dxf)

No. You can use this way, but the best way is to restore the nuget package.
