### ISSUE TITLE
Need to know steps to run this project

### ISSUE THREAD

**Issue by chetan-SMRI** [fel88/DeepNestPort#18]
Please tell me how to run this project and generate a exe, i am a newbie to C# and C++. However i have previous experience in python.

**Comment by fel88** [comment]
Just open solution file (*.sln) in a Visual Studio and press Build->Build solution

You'll find an .exe file in bin\Debug subdirectory. DeepNestConsole.exe (Console version) and DeepNestPort.exe (GUI version) 

C++ is not nessecarily for this project.

**Comment by chetan-SMRI** [comment]
So we just have to download this project zip and install vs2022.
Then open the folder in vs software and click build?
thats all we need to run it?

**Comment by fel88** [comment]
Just set UseExternalDll (Background.cs) flag to false. Also you can disable it in the GUI (settings tab, 'use external Dll' checkbox)

**Comment by fel88** [comment]
> hey bro i got it running after creating own dll.(I have done a readme update request, plz check and refractor if needed)

I've merged your build instruction. I think someone will find it useful. 

> ... in Deepnest we could do these things with easy and it was much GUI friendly

If you have any ideas how to improve current project/GUI, let me know in the Discussions

**Comment by chetan-SMRI** [comment]
I just wanted to know which thing u updated recently? Also I have some ideas regarding GUI,  

But firstly, I think we should rather update some features in the application itself, 
1) instead of showing values in pixel format we should rather show it in the inch format which is most used in this industry and is industry standard.
2) we should do show sheets correctly , in the current application it is difficult to view sheets and zoom is also not possible(we can copy code for this from Deepnestsharp)
3) DXF differentiator is needed, like in deepnest if u import any svg then if it has parts then they are automatically differentiated, but in your application they remain grouped as a single part.

After these important changes we can move to improve GUI .
Also tell me if u want to collab, I am a python developer but I have previously worked on C# so I will be able to help as much as I can do.

**Comment by chetan-SMRI** [comment]
please come in discussion to chat more
