### ISSUE TITLE
Correct usage?

### ISSUE THREAD

**Issue by software6ptk** [fel88/DeepNestPort#23]
Hi,
im' trying to use this library as an external dll

as of now, i create a sheet and add it to context sheets
then i create polygons and add them to context polygons
i call StartNest, then i NestIterate for a given time span (tried up to 10 seconds, i'm testing with a low number of shapes made up by low number of points so time should not be an issue)

after that i try to take back the nested shapes by rotating and offsetting each point by the rotation and offsetx/y given by the context.Polygons property

result is not what i expected, as shapes are not actually in nested position.

What am i doing wrong?

Thanks in advance for the answer.

EDIT:
don't know if this could be useful but this is what i get trying to nest three stars
![image](https://github.com/fel88/DeepNestPort/assets/141343509/9851a697-4738-4111-8cd2-bdd807e6a674)

**Comment by fel88** [comment]
Hi, have you seen https://github.com/fel88/DeepNestPort/tree/master/Framework/DeepNestConsole ?
It can be exactly what you want

**Comment by software6ptk** [comment]
Good afternoon and thank you for your time.

Unfortunately that only does a conversion to xml in the sample and doesn't show me how to manually extract the nested shapes

what i need is the ability to take the nested points data so that i can use them with other things.

Did i explain my problem well enough?
