### ISSUE TITLE
Compiling boost for Mac

### ISSUE THREAD

**Issue by petrasvestartas** [fel88/DeepNestPort#9]
Hi,

How can I compile the Minkowski of Boost for Mac?

Thanks,
Petras

**Comment by kelyamany** [comment]
I needed to use the tool as a command line utility to be called from other scripts in a Linux environment so you might find these changes in this fork:
https://github.com/kelyamany/DeepNestPort

I've upgraded the project to .NET 5 and added a conditional build for the Minkowski library to either build for Windows or Linux, didn't try Mac though but I think it might be similar to the Linux build maybe?

Maybe you can add the build configuration to this file:
https://github.com/kelyamany/DeepNestPort/blob/7a5d882ad692ed7b8195dcb7ad9c077ce7304d71/CMakeSettings.json

@fel88 maybe we can integrate these changes into the main repo somehow if they are useful?

**Comment by fel88** [comment]
> @fel88 maybe we can integrate these changes into the main repo somehow if they are useful?

Cross-platform stuff (conditional build, cmake etc) could be useful indeed. 
Dxf import/export in the console app can be integrated as well.

**Comment by kelyamany** [comment]
Sure, I'll filter these changes later and create a pull request with them(because I was experimenting other stuff with the nesting performance too that might not be relevant and some problems with fitness resulting to be NaN)

but overall, great job @fel88. It's a very useful project indeed :))
